In [4]:
import numpy as np

Basic Array Creation

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

In [7]:
a = [1,2,3,4, "hello", 2.4] #Multiple data types
a

[1, 2, 3, 4, 'hello', 2.4]

In [8]:
np.array(a) # Datatype of all elements get converted into string

array(['1', '2', '3', '4', 'hello', '2.4'], dtype='<U32')

In [9]:
b = [1,2,3,4, 2.4]
np.array(b) # Everything gets converted into float

array([1. , 2. , 3. , 4. , 2.4])

### Vectors and Matrices
- Vectors are one-dimensional, formed through list
- Matrices are two-dimensional, formed through numpy array
- Multi-dimensional matrices are termed as Tensors

In [10]:
l = [[1,2,3],[4,5,6],[7,8,9]] # vector
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(l) # Now this becomes a matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Function

In [12]:
# Generating array from 1 to 10 with 2 steps
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [13]:
arr = np.zeros(6) # Vector form
arr

array([0., 0., 0., 0., 0., 0.])

In [14]:
arr = np.zeros((4,8)) # 4 Rows and 8 columns
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
arr = np.ones((3,2))
arr


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
#Linear Spacing -- Provides array in linearly spaced format within a certified range

arr = np.linspace(1,5,2)
arr


array([1., 5.])

In [17]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [18]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

Random Generation Function

In [19]:
np.random.rand(10) # 10 Random numbers between 0 and 1 (Normalization) 

array([0.38245965, 0.01151818, 0.48425104, 0.2769807 , 0.57190632,
       0.08750745, 0.46717749, 0.99749067, 0.86260682, 0.00280029])

In [20]:
np.random.randn(10) # Standardization

array([ 1.05358076, -1.68294941,  0.83984769, -1.02708385, -0.85698445,
       -0.70877927, -0.88689981, -1.32506243,  1.1570925 , -1.28182234])

In [21]:
np.random.randint(6) # between 0 to 6

0

In [22]:
np.random.randint(10,20,10)

array([14, 11, 16, 19, 19, 17, 17, 12, 13, 15], dtype=int32)

Array Attributes

In [23]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr.shape # no brackets() because this is an attribute not a method

(3, 3)

In [25]:
arr.size

9

In [26]:
arr.dtype

dtype('int64')

Array Methods

In [27]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr.min()

np.int64(1)

In [29]:
arr.max()

np.int64(9)

In [30]:
arr.sum()

np.int64(45)

In [31]:
np.sum(arr, axis=0) # Summation of array elements, axis=0 is for column

array([12, 15, 18])

In [32]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [33]:
arr.mean()

np.float64(5.0)

In [34]:
# Standard Deviation
arr.std()

np.float64(2.581988897471611)

In [35]:
# Index position of maximum element
arr.argmax()

np.int64(8)

In [36]:
# Index position of minimum element
arr.argmin()

np.int64(0)

Reshaping and Resizing

In [37]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [42]:
# arr.reshape(5,5) # throws error
# Always keep in mind while reshaping that the order of shape should be such that all elements should accomodate
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])