In [1]:
import numpy as np

Numpy Indexing and Slicing of Vectors
(Same as of list in Python)

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[3]

np.int64(14)

In [6]:
arr[1:5]

array([12, 13, 14, 15])

In [8]:
arr[:4]

array([11, 12, 13, 14])

In [9]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[3::]

array([14, 15, 16, 17, 18, 19, 20])

In [12]:
arr_slice = arr[2:9:2]
arr_slice

array([13, 15, 17, 19])

Numpy Indexing and Slicing of Matrix

In [13]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0] # Prints 0th row

array([1, 2, 3, 4, 5])

In [15]:
arr[5]

array([26, 27, 28, 29, 30])

In [17]:
arr[0,2]

np.int64(3)

In [18]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
arr[5,4]

np.int64(30)

In [21]:
arr[5,0:4]

array([26, 27, 28, 29])

In [24]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [23]:
arr[0:,1]

array([ 2,  7, 12, 17, 22, 27])

In [25]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [27]:
arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25],
       [30]])

In [28]:
arr[:,1:2]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22],
       [27]])

Boolean Indexing

In [32]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
# to get only even numbers

bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [35]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])