### _Array Operations_

In [1]:
import numpy as np

Arithmetic Operations

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [9]:
add = a1 + a2 # size of both arrays should be same
add

array([ 7,  9, 11, 13, 15])

In [8]:
mul = a1 * a2
mul

array([ 6, 14, 24, 36, 50])

In [7]:
sub = a1 - a2
sub

array([-5, -5, -5, -5, -5])

In [11]:
div1 = a1/a2
div1

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [12]:
floor_div = a1 // a2
floor_div

array([0, 0, 0, 0, 0])

In [14]:
exp = a1 ** a2
exp

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [17]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [18]:
# For increment of 10 in every element

arr + 10

array([20, 30, 40, 50])

In [20]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [23]:
arr2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

Deep and Shallow copy

In [45]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
slice = a[:4]
slice

array([1, 2, 3, 4])

In [ ]:
slice = slice * 10 # Slicing takes a new different location in memory --> Deep Copy
slice

array([10, 20, 30, 40])

In [32]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
a[4:6] * 10

array([50, 60])

In [46]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
# b = a # both have same location in the memory --> Shallow Copy
b = a.copy() # --> Deep Copy
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [52]:
A = np.array([[1,2,],[3,4]])
B = np.array([[5,6,],[7,8]])

In [58]:
A

array([[1, 2],
       [3, 4]])

In [59]:
B

array([[5, 6],
       [7, 8]])

In [57]:
# Wrong Matrix Multiplication
A * B

array([[ 5, 12],
       [21, 32]])

In [56]:
mat_mul = A @ B
mat_mul

array([[19, 22],
       [43, 50]])

In [60]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [61]:
A.T

array([[1, 3],
       [2, 4]])

In [62]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

### Advanced Array Manipulation

Stacking Array
- We cannot stack two matrices, because they are already stacked arrays

In [63]:
A

array([[1, 2],
       [3, 4]])

In [64]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
# For stacking, we use vectors
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
#Vertical Stack
np.vstack((a,b)) # gives 2-D array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal Stack
np.hstack((a,b)) # gives 1-D array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Column stack
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array
- Splits into 2-D matrix

In [69]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
# Horizontal Split
np.hsplit(c,2) # You need to have equal divisions for split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.hsplit(c,3) # Throws error because 4 cannot be divided into three parts

In [75]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]