In [2]:
import numpy as np

## *Valid Sudoku*
- A sudoku is valid iff all individual rows and columns have there individual sum as 45

In [15]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2], # For every row, the sum of the elements should be 45
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [7]:
# s.sum()
r = np.sum(s,axis=1) # Each and every row has a sum of 45
r == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [8]:
for i in r:
    if i != 45:
        print("Sudoku is invalid")
        break

else:
    print("for rows Sudoku is valid")

for rows Sudoku is valid


In [9]:
c = np.sum(s,axis=0)
c == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [10]:
for i in c:
    if i != 45:
        print("Sudoku is invalid")
        break

else:
    print("For columns Sudoku is valid")

For columns Sudoku is valid


In [12]:
d1 = np.sum(s[0:3,0:3])
d1

np.int64(45)

In [19]:
d2 = np.sum(s[0:3,3:6])
d2

np.int64(45)

In [29]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [30]:
l = list()
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        l.append(n.sum().item()) # n.sum() this gives Numpy scalar np.int64(45)
                                 # n.sum().item() gives Python scalar 45

l

[45, 45, 45, 45, 45, 45, 45, 45, 45]

## *General Questions*

In [67]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

Get the shape of the matrix

In [33]:
# Get the shape of the matrix
data.shape

(5, 3)

Find the average age of students

In [34]:
# Find the average age of students
np.mean(data[:,0])

np.float64(18.4)

Extract Math marks of all students

In [35]:
# Extract Math marks of all students
data[:,1]

array([85, 92, 76, 65, 90])

Find the highest Science marks

In [36]:
# Find the highest Science marks
np.max(data[:,2])

np.int64(95)

Get details of the student who scored more than 90 in Math

In [38]:
# Get details of the student who scored more than 90 in Math
data[data[:,1] > 90]

array([[19, 92, 88]])

In [55]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [68]:
# Increase Math marks of all students by 5.

data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [58]:
# Find how many students are younger than 19

len(data[data[:,0] < 19])

3

In [62]:
# Calculate the average marks in each subject (column-wise mean)

np.mean(data[:,1:], axis=0)

array([86.6, 83.2])

In [64]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [63]:
# Get data of students who scored at least 80 in both subjects.

data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [70]:
# Replace all Science marks < 75 with 0.

data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])

In [73]:
mask = data[:,2] < 75
mask
data[mask, 2] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])