In [2]:
import numpy as np

### **Valid Sudoku**
- A Sudoku is valid if it fulfills following conditions:
    - It should have total matrix size of (9,9)
    - Every row and column should have unique elements between 1 to 9, such that no element repeats again
    - Every row should have sum of 45

In [34]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [4]:
# Verify that if this is a valid Sudoku based on the condition given

In [5]:
s.shape

(9, 9)

In [ ]:
for row in s:
    if len(set(row)) != 9:
        print('Invalid Sudoku')
        break
    else:
        for col in s.T:
            if len(set(col)) != 9:
                print('Invalid Sudoku')
                break
else:        
    print('Valid rows and columns')

Invalid Sudoku


In [26]:
for row in s:
    if len(set(row)) != 9:
        print('Invalid Sudoku')
        break

# print('Valid rows and columns')

for col in s.T:
    if len(set(col)) != 9:
        print('Invalid Sudoku')
        break
       
print('Valid rows and columns')

Invalid Sudoku
Invalid Sudoku
Valid rows and columns


In [35]:
r = np.sum(s, axis=1)
r == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [37]:
for i in r:
    if i != 45:
        print('Invalid Sudoku')
        break
else:
    print('Valid Sudoku')

Valid Sudoku


**General Questions**

In [46]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [39]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [40]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [41]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [42]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [43]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]


array([[19, 92, 88]])

In [ ]:
#Increase Math marks of all students by 5.
data[:,1] + 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [53]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])

In [48]:
#Find how many students are younger than 19.
len(data[data[:,0] < 19])

3

In [49]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:], axis=0)

array([86.6, 83.2])

In [50]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [51]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0

In [52]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])